data_config:
  raw_data_path: "artifacts/data"
  processed_data_path: "artifacts/processed_data"
  train_data_file: "youtube_dataset_with_full_countries.csv"
  thumbnail_features_file: "thumbnail_features.csv"
  min_samples_required: 10
  required_columns:
    - "video_id"
    - "title"
    - "view_count"
    - "category"
    - "country"
    - "genre"
    - "duration"
    - "upload_time"
    - "subscribers"

model_config:
  target_column: "view_count"
  test_size: 0.2
  random_state: 42
  skip_train_test_split_if_small: True
  quantiles: [0.05, 0.25, 0.5, 0.75, 0.95]  # Added quantile configuration

train_config:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    random_state: 42
  lightgbm:
    n_estimators: 50
    learning_rate: 0.1
    max_depth: 5
    objective: "quantile"  # Updated for quantile regression
    metric: "quantile"     # Updated for quantile regression