data_config:
  raw_data_path: "artifacts"
  train_data_file: "youtube_dataset_with_full_countries.csv"
  thumbnail_features_file: "thumbnail_features.csv"
  processed_data_path: "artifacts/processed_data"
  min_samples_required: 50

model_config:
  target_column: "view_count"
  test_size: 0.2
  random_state: 42
  quantiles: [0.4, 0.45, 0.5, 0.55, 0.6]  # Narrow range
  target_range: [30000, 50000]  # Desired output range

train_config:
  lightgbm:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.03
    min_child_samples: 30
    reg_alpha: 0.2
    reg_lambda: 0.2
    subsample: 0.8
    colsample_bytree: 0.8